FROM python:3.11-slim

WORKDIR /app

# Copy requirements first
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy all backend code
COPY . .

# Set production Flask environment
ENV FLASK_ENV=production
ENV PYTHONUNBUFFERED=1

# Install Gunicorn
RUN pip install gunicorn

# Expose default port for clarity
EXPOSE 5001

# Start Gunicorn with dynamic Render port
CMD gunicorn -w 4 -b 0.0.0.0:$PORT app:app